function ViewModel() {
	var self = this;

	self.floors = ko.observableArray(allFloors)

    self.items = ko.observableArray([
		[{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'black'}],

		[{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'black'}],
		[{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'green'},
		{"color": 'green'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'black'}],

		[{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'black'}],
		[{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'black'}],
		[{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'black'}],
		[{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'black'}],

		[{"color": 'white'},
		{"color": 'white'},
		{"color": 'black'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'}],

		[{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'black'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'}],

		[{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'}],

		[{"color": 'white'},
		{"color": 'white'},
		{"color": 'black'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'}],

		[{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'black'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'black'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'}],

		[{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'}],

		[{"color": 'white'},
		{"color": 'white'},
		{"color": 'black'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'}],

		[{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'black'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'},
		{"color": 'white'}],
	]);
    self.items_grouped = ko.computed(function(){
        var grouped = [];
        var itemlist = self.items();
        for(var i = 0; i < itemlist.length; i++){
            var row = [];
            for(var j = 0; j < itemlist[i].length; j++){
                row.push(itemlist[i][j]);
			}
			grouped.push(row);
        }
        return grouped;
    });
}

ko.applyBindings(new ViewModel())